name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
#  test-ubuntu:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [3.6, 3.7, 3.8, 3.9]
#        jdk-distribution: ['zulu', 'adopt']
#        jdk-version: [ '8', '11', '13', '15' ]
#        test-file: ['sample.py', 'sample2.py']
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup python
#        uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Check python version
#        run: python --version
#      - name: Setup Java JDK
#        uses: actions/setup-java@v2.1.0
#        with:
#          distribution: ${{ matrix.jdk-distribution }}
#          java-version: ${{ matrix.jdk-version }}
#      - name: Check java version
#        run: java -version
#      - name: Install requirements.txt
#        run: pip install -r requirements.txt
#      - name: Run sample
#        run: python ${{ matrix.test-file }}
  test-centos:
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'centos:7', 'centos:8' ]
        java-package: [ 'java-11-openjdk', 'java-1.8.0-openjdk' ]
        python-package: [ 'python36', 'python38' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install java
        run: yum install -y ${{ matrix.java-package }}
      - name: Check java version
        run: java -version
      - name: Install python
        run: yum install -y ${{ matrix.python-package }}
      - name: Check python version
        run: python --version
  test-redhat:
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'centos:7', 'centos:8' ]
        java-package: [ 'java-11-openjdk', 'java-1.8.0-openjdk' ]
        python-package: [ 'rh-python36', 'rh-python38' ]
    steps:
      - uses: actions/checkout@v2
      - name: Install java
        run: yum install -y ${{ matrix.java-package }}
      - name: Check java version
        run: java -version
      - name: Install python
        run: yum install -y ${{ matrix.python-package }}
      - name: Check python version
        run: python --version

