# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Set the python versions to be installed and run of
        python-version: [3.6, 3.7, 3.8, 3.9]
        jdk-distribution: ['zulu', 'adopt']
        jdk-version: [ '8', '11', '13', '15' ]
        test-file: ['sample.py']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check python version
        run: python --version
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: ${{ matrix.jdk-distribution }}
          java-version: ${{ matrix.jdk-version }}
      - name: Check java version
        run: java -version
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Run sample
        run: python ${{ matrix.test-file }}
